llm:
  api_type: "openai"
  base_url: "https://api.openai.com/v1"
  model: "gpt-4o"
  api_key: "YOUR_API_KEY"
  max_concurrent: 20

embedding:
  api_type: "hf"
  model: "./Embedding_Model/bge-m3"
  cache_dir: ""
  dimensions: 1024
  max_token_size: 8192
  embed_batch_size: 16
  embedding_func_max_async: 16

data_root: "./Data"

working_dir: ./Result/HyGRAG/
exp_name: experiment
